language: go
go:
  - 1.1
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/apcera/gnatsd
  - go get -v ./...
  - go build -v ./...

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - go test -v ./...
